# index:
#    path: /home
#    controller: App\Controller\UserController::homepage

oauth_check:
  path: /oauth/check/{service}
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController;